### ISSUE TITLE
README: Add a glorious Screenshot of openSUSEway 

### ISSUE THREAD

**Issue by taschenlampe** [openSUSE/openSUSEway#93]
Hi!
I know this is just cosmetics...but I think a screenshot of oSw in README would make itself nice, as oSw isn´t an ugly duckling ;-)
Cheers

**Comment by jubalh** [comment]
Feel free to send a PR.

There is also a screenshot at: https://en.opensuse.org/Portal:OpenSUSEway

BTW: maybe someone can check whether the site is still up to date.

**Comment by FilippoBonazziSUSE** [comment]
I was going to provide a screenshot, but I use a somewhat modified configuration on top of openSUSEway so it wouldn't be right. So I tried taking a screenshot in my openSUSEway stock VM, but `neofetch` reports the wrong resolution and you can also tell it's inside a VM, so that's not the best either.

Any takers?
